name: Setup RDP with Ngrok

on:
  push:
    branches:
      - main

jobs:
  setup-rdp-ngrok:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download Ngrok
      run: |
        Invoke-WebRequest -Uri https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath $env:USERPROFILE
        $env:PATH += ";$env:USERPROFILE\ngrok.exe"

    - name: Authenticate Ngrok
      run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Ngrok TCP Tunnel for RDP
      run: |
        ngrok tcp 3389 --log=stdout &
        timeout /t 10
        echo "Ngrok tunnel started"
